/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_megvii_jnidemo_handler_NativeWorker */

#ifndef _Included_com_megvii_jnidemo_handler_NativeWorker
#define _Included_com_megvii_jnidemo_handler_NativeWorker

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_megvii_jnidemo_handler_NativeWorker
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_megvii_jnidemo_handler_NativeWorker_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
